---
title: Academic networks & public profiles
author: Jeffrey S. Racine
date: '2018-06-23'
slug: academic-networks-public-profiles
categories: []
tags: []
header:
  caption: ''
  image: ''
---

Knowledge transfer and the dissemination of research are vital components of the academic mission, yet sometimes these are afforded no more than an afterthought.

I strive to impress upon my students and colleagues the often overlooked importance of replicability, automated backup procedures, and version control. But dissemination of work via academic conferences, being a visible member of the international academic community, and in general "marketing" our research to others often gets short shrift. 

It is a shame when one spends months and sometimes years engaged in a research project yet no one is aware of the work, even when it eventually appears in print. "If a tree falls..." comes to mind.

The past decade has witnessed exponential growth in the number of social media outlets designed for the general public. Similar growth has occurred for *academic* social media outlets and other hosting platforms. Some of the more popular in my field include

- [GitHub <i class="fa fa-github"></i>](https://github.com)

    GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside millions of other developers. GitHub has a strong commitment to education (visit the [Github Education Site](https://education.github.com) for details).

- [Google Scholar <i class="ai ai-google-scholar"></i>](https://scholar.google.ca)

    Google Scholar provides a simple way to broadly search for scholarly literature. Google Scholar Citations provide a simple way for authors to keep track of citations to their articles. You can check who is citing your publications, graph citations over time, and compute several citation metrics.

- [IDEAS/RePEc <i class="ai ai-ideas-repec"></i>](https://ideas.repec.org)

    IDEAS is the largest bibliographic database dedicated to Economics and available freely on the Internet, based on RePEc. RePEc is a large volunteer effort to enhance the free dissemination of research in Economics which includes bibliographic metadata from over 2,000 participating archives, including all the major publishers and research outlets.

- [Impactstory <i class="ai ai-impactstory"></i>](https://impactstory.org)

    Impactstory is an open source, web-based tool that provides altmetrics to help researchers measure and share the impacts of all their research outputs—from traditional ones such as journal articles, to alternative research outputs such as blog posts, datasets, and software.

- [Mendeley  <i class="ai ai-mendeley"></i>](https://www.mendeley.com)

    Mendeley is a free reference manager and an academic social network for managing and sharing research papers, discovering research data and collaborating online.
    
- [ORCID <i class="ai ai-orcid"></i>](https://orcid.org)

    ORCID provides a persistent digital identifier that distinguishes you from every other researcher and, through integration in key research workflows such as manuscript and grant submission, supports automated linkages between you and your professional activities ensuring that your work is recognized.

- [ResearchGate <i class="ai ai-researchgate"></i>](https://www.researchgate.net)

    ResearchGate is a social networking site for scientists and researchers to share papers, ask and answer questions, and find collaborators.

- [Scopus](https://www.elsevier.com/solutions/scopus)
    
    Scopus is the largest abstract and citation database of *peer-reviewed* literature: scientific journals, books and conference proceedings.    
    
It doesn't take much effort to create a profile, organize your publications and activities and add some basic information about your academic status, education, and research interests. Even though there may be some overlap among the services, by creating each of these profiles you can give the visibility of your research a potential boost.

One tip I might offer is that you occasionally log into your profiles and ensure that they accurately reflect your record and are current (perhaps a calendar entry twice a year would be worth the effort - the same goes for your personal and academic websites, naturally).