---
title: GitHub Education and Private Repositories
author: Jeffrey S. Racine
date: '2018-06-01'
slug: github-education-and-private-repositories
categories: []
tags: []
header:
  caption: ''
  image: ''
---

Yesterday I was discussing workflow with a PhD student who I recently started supervising, and I encouraged her to get up to speed with [GitHub](https://github.com), which she did. I also discussed how I use GitHub for working with co-authors on R packages by adding them as "contributors" to a GitHub repository. 

I further suggested that this would be an ideal way for me to guide her through the process of writing her dissertation since, for one, tracking changes is trivial and relieves me of having to re-read chapters multiple times. 

Voicing privacy concerns, I asked the student to look into creating private repositories which, I understood, were a GitHub feature that GitHub charged for. She did a quick search, located the [GitHub Education site](https://education.github.com) and the [Github Student Pack](https://education.github.com/pack/join) which now provides an unlimited number of private repositories for free for as long as you remain a student, subscribed and added me as a contributor to a new private repository. So far so good!

Then I took a quick peek, stumbled upon the link ["No, I'm not a student but would still like a discount"](https://education.github.com/discount_requests/new), and submitted a request with a brief explanation of why I would like access to private repositories. I expected, if anything, a slight discount to the regular monthly fee ($7). Instead, I immediately received an email response stating

> "Hey Jeffrey S. Racine, we have some awesome news. We've upgraded you to a plan with unlimited free private repositories, which will be free for the next two years. After that, you'll get an email saying that your coupon is expiring. You can reapply for another coupon if you still have academic status. We don't have any collaboration limits, so any group projects you may encounter can be hosted via your account."

Needless to say, I am grateful for this service as it allows me to collaborate with students and co-authors privately via GitHub for early-stage projects (once a project has resulted in a paper ready for circulation, I place that in the public sphere as a [working paper on IDEAS/RePec](https://ideas.repec.org/s/mcm/deptwp.html)). Perhaps this previously unknown service might be of value to other academics, hence this post.