---
title: RStudio Cloud is in alpha
author: Jeffrey S. Racine
date: '2018-05-27'
slug: rstudio-cloud-is-in-alpha
categories: []
tags: []
header:
  caption: ''
  image: ''
---

I am constantly on the lookout for new tools and ways of conducting my research and engaging in knowledge transfer, whether in the classroom or otherwise. I recently stumbled upon RStudio Cloud (https://rstudio.cloud) which combines cloud computing, RStudio server, and `spaces' that allow you to publicy share work or work privately with a group (say, a group of students). No configuration is needed, there is no need to install R or RStudio or TeX or github locally (though both can coexist, naturally). It appears that this could be a killer application in the classroom while it also offers a number of tantalizing features. For instance, computing on a tablet or phone is possible with the computing being done on cloud cores, all in a simple browser interface that is indistinguishable from that you would encounter in the desktop version. One can upload existing R scripts, use R Markdown, bookdown, and notebooks, among others.